package com.pnm.auth.enums;

public enum AuditAction {

    // USER ACTIONS
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    MFA_OTP_VERIFIED,
    RISK_OTP_VERIFIED,
    LOGOUT,
    PASSWORD_CHANGED,
    EMAIL_CHANGED,
    MFA_ENABLED,
    MFA_DISABLED,
    TRUSTED_DEVICE_ADDED,
    TRUSTED_DEVICE_REMOVED,

    // ADMIN ACTIONS
    ADMIN_USER_BLOCKED,
    ADMIN_USER_UNBLOCKED,
    ADMIN_USER_DELETED,
    ADMIN_USER_ROLE_UPDATED,

    // SYSTEM ACTIONS
    RISK_SUSPICIOUS_LOGIN,
    IMPOSSIBLE_TRAVEL_DETECTED,
    MULTI_ACCOUNT_IP_DETECTED;
}
